# Generated by Django 5.1.6 on 2025-02-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_reminder_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('networking', 'Networking Event')], max_length=20)),
                ('number_of_tickets', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
